---
 - hosts: all
   remote_user: vagrant
   gather_facts: yes
   ignore_errors: yes
   become: true
   tasks:
    - name: shutdown the machines if it is RHEL OS
      shell: shutdown
      when: ansible_os_family == "RedHat"