# ---
  - hosts: all
    remote_user: vagrant
    gather_facts: no
    tasks: 
      - shell: "cat /etc/sysctl/db.conf"
        register: results
      - debug:
          #msg: "{{ df_results.stdout }}"
          #msg: "{{ df_results.stdout_lines }}"
          #msg: "{{ results.stdout_lines }}"
           msg: "{{ results.stdout_lines }}"
